### ISSUE TITLE
Override behavior of Underscores in result set column names

### ISSUE THREAD

**Issue by Vijaykumarj** [verdie-g/StoredProcedureEFCore#13]
Can u guide to how to Override the behavior of "Underscores in result set column names ("column_name" is mapped to ColumnName property)" Becoz my Model class already used in mobile & some another clients.

**Comment by verdie-g** [comment]
Ok, I can add a method to IStoredProcBuilder to override the removal of underscore.

**Comment by Vijaykumarj** [comment]
thanks a lot for accepting of my request. 
May i know when it will be released of this feature.
thanks in advance.

**Comment by verdie-g** [comment]
I realize it is a heavy feature. I won't have time to do it. Can you still fork the project, the removal of the underscores is here : https://github.com/verdie-g/StoredProcedureEFCore/blob/develop/StoredProcedureEFCore/Mapper.cs#L92

**Comment by Vijaykumarj** [comment]
thank u @verdie-g. I will be fork it.
