### ISSUE TITLE
Cannot cancel

### ISSUE THREAD

**Issue by IlyaTsilikovRAFrame** [verdie-g/StoredProcedureEFCore#14]
I see `IStoredProcBuilder.ExecNonQueryAsync ()`, etc. without `CancellationToken` parameter. Ability to cancel is often important.

**Comment by verdie-g** [comment]
I think you cancel like that :

```csharp
var cts = new CancellationTokenSource();
Task t = ctx.LoadStoredProc("").ExecNonQueryAsync();
ctx.Wait(cts.Token);
```

Is it important to add a CancellationToken to the api ?

**Comment by IlyaTsilikovRAFrame** [comment]
I think it's important 'cause such or similar way I can just cancel call awaiting but not a procedure execution itself. But the embedded command cancellation can cancel also a procedure execution.
