### ISSUE TITLE
Using Exec ToList() with generic T

### ISSUE THREAD

**Issue by Dunsteer** [verdie-g/StoredProcedureEFCore#18]
I have a problem with executing a stored procedure, It works with a class but does not want to compile with generic type.
Here is my code
```cs
List<T> list = null;

_dbContext.LoadStoredProc($"dbo.{procedure_name}")
 .AddParam("max_rv", out IOutParam<byte[]> lastRVFromProcedure)
.Exec(r => list = r.ToList<T>());
```

And this is the error I get

Error	CS1929	'DbDataReader' does not contain a definition for 'ToList' and the best extension method overload 'ParallelEnumerable.ToList<T>(ParallelQuery<T>)' requires a receiver of type 'ParallelQuery<T>'

Edit

How do I use InOut params for the procedure?

**Comment by verdie-g** [comment]
Hello, they are two constraints on the T which are class and new(). See [DbDataReaderExtension.ToList](https://github.com/verdie-g/StoredProcedureEFCore/blob/master/StoredProcedureEFCore/DbDataReaderExtension.cs#L19)

**Comment by Dunsteer** [comment]
Thanks, I figured it out, maybe you should add it to the summery of the ToList extension
