### ISSUE TITLE
Concurrent calls to MapColumnsToProperties generate multiple times the setter

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/StoredProcedureEFCore#21]

**Comment by vassilvk** [comment]
Hi @verdie-g, can you please add more detail to this issue?

Thanks!

**Comment by verdie-g** [comment]
https://github.com/verdie-g/StoredProcedureEFCore/blob/86a6be01a1da3e1a61f96db6171b5a808210fe01/StoredProcedureEFCore/Mapper.cs#L98-L101

Here, a setter is generated and then cached into a dictionary. If two threads call ToList for the first time for a model not yet cached the setter will be generated twice and both will be inserted in the dictionary, the last one overwriting the first one. This might cause a leak, is it what you are experiencing ?

**Comment by verdie-g** [comment]
According to https://stackoverflow.com/a/5340444/5407910 the generated code can be garbage collected so the impact is low.
