### ISSUE TITLE
Awaited async calls capture and re-enter the synchronization context which may lead to deadlocks

### ISSUE THREAD

**Issue by vassilvk** [verdie-g/StoredProcedureEFCore#28]
The library does not `.ConfigureAwait(false)` on all internal `await` calls, thus it unnecessarily captures the synchronization context.

This may lead to deadlocks:
http://www.tugberkugurlu.com/archive/the-perfect-recipe-to-shoot-yourself-in-the-foot-ending-up-with-a-deadlock-using-the-c-sharp-5-0-asynchronous-language-features

**Comment by vassilvk** [comment]
@verdie-g - please note that I am working on a pull request to resolve the above.

**Comment by verdie-g** [comment]
Yep, I'm aware of this issue. I didn't use ConfigureAwait because I've always used this library in full asynchronous scenarios where waiting on a Task is not allowed. If you need it though, feel free to open your pull request.
