### ISSUE TITLE
Is there an EF Core 3.0 version?

### ISSUE THREAD

**Issue by bobskigit** [verdie-g/StoredProcedureEFCore#35]

**Comment by VahidN** [comment]
EF Core 3x supports SPs. Here is a sample about it, if anyone is interested: 
[EFCore3SPs.zip](https://github.com/verdie-g/StoredProcedureEFCore/files/4280287/EFCore3SPs.zip)

**Comment by bobskigit** [comment]
But Your syntax is better and more readable, addParams("xx", value) and easier to handle in/out params and return params.

**Comment by verdie-g** [comment]
You should be able to use the library with EF Core 3. What's your issue?
