### ISSUE TITLE
.Net Core 3.1 version?

### ISSUE THREAD

**Issue by gtrbarbarian** [verdie-g/StoredProcedureEFCore#37]
Hi, yes I know I can send SQL down through ExecuteSQLCommand. Your library is better, obviously. The source should compile with a change to .Net Standard 2.1 to be usable with core 3.1. 

This is the price of doing something well: People want to continue using it!

Let me know if this is in the works, and thanks!

**Comment by verdie-g** [comment]
Hello, this library targets .NET Standard 2.1, you should be able to reference it from a .NET Core 3.1 project.

**Comment by gtrbarbarian** [comment]
Am I missing something? Via Nuget.org, and Manage Nuget Packages in visual studio, I see 1.0.2, which lists as dependencies, .Net Standard **2.0**. I also have pre-release checked to make sure I'm not missing a beta package. Pic link attached. Thanks in advance!

[imgur link to pics](https://imgur.com/a/PxYlnRx)

**Comment by verdie-g** [comment]
Sorry it targets .NET Standard 2.0 😅 but it can still be referenced from a .NET Core 3.1 library.

**Comment by gtrbarbarian** [comment]
Thank you.
