### ISSUE TITLE
Add support for SqlBytes

### ISSUE THREAD

**Issue by jkatsiotis** [verdie-g/StoredProcedureEFCore#38]
I'm currently trying to use this lib with NetTopologySuite to map geography columns.

Any help would be much appreciated.

Thanks!

**Comment by verdie-g** [comment]
Hello, I'm lacking some context here. What are you trying to do? Are you using SQL Server and trying to read a column of type `varbinary`?

**Comment by jkatsiotis** [comment]
I apologize. What I was trying to do is pass an input parameter to a stored procedure. The type was varbinary.

However I solved it by using the ToString method of my spatial object and it works. Nothing else to do on your end.
