### ISSUE TITLE
Using with Transaction - This SqlTransaction has completed

### ISSUE THREAD

**Issue by jkatsiotis** [verdie-g/StoredProcedureEFCore#39]
I have the following scenario:

1. Open a DbTransaction
2. Perform updates (using SaveChanges() )
3. Run a stored procedure using LoadStoredProc
4. Perform more updates (again using SaveChanges() )
5. Commit the transaction

When I commit the transaction a get the error :This SqlTransaction has completed; it is no longer usable.

However I've tested the following:

Removing and not execute at all the SP from the above step 3 (and it works)
Replacing LoadStoredProc with ExecuteSqlRaw where I execute the SP using EF's API (and it works)

That's my SP dependent code:

```
this.LoadStoredProc("MySP")
.AddParam("LotID", lotId)
.Exec(reader => result = reader.ToList<Result>());
```

Using SQL Server - EF Core 3.0

Any insights?

**Comment by verdie-g** [comment]
Hello, could you share a full example of the issue?

**Comment by jkatsiotis** [comment]
Sure. Two samples below. One that works and one that doesn't.

```
//this doesn't work
using (var ts = context.Database.BeginTransaction()) {
    //do changes
    model.DoChanges();
    context.SaveChanges();

    //run SP
    context.LoadStoredProc("MySP")
        .AddParam("LotID", lotId)
        .Exec(reader => result = reader.ToList<Result>());

    model.DoChanges();
    context.SaveChanges();

    ts.Commit();
}

```
The code below works

```
//this works 
using (var ts = context.Database.BeginTransaction()) {
    //do changes
    model.DoChanges();
    context.SaveChanges();

    //run SP
    context.Database.ExecuteSqlRaw("EXEC MySP @LotID={0}", lotId);

    model.DoChanges();
    context.SaveChanges();

    ts.Commit();
}
```

**Comment by jkatsiotis** [comment]
Hi, did you manage to replicate the issue? Is there a workaround?

**Comment by jkatsiotis** [comment]
Check this: https://stackoverflow.com/questions/1539564/what-happens-to-an-uncommitted-transaction-when-the-connection-is-closed

 If you dispose a connection with pending transactions, it will rollback.

So, I'm guessing that Dispose functionality that has been implemented causes this issue.

**Comment by verdie-g** [comment]
That's probably the issue
