### ISSUE TITLE
It seems that impossible to call SP which has output sql_variant parameters

### ISSUE THREAD

**Issue by guffy1234** [verdie-g/StoredProcedureEFCore#41]
As an example, it's impossible to call systems stored procedure to get range from a sequence:

            this.LoadStoredProc("sys.sp_sequence_get_range")
                .AddParam("sequence_name", sequence)
                .AddParam("range_size", range_size)
                .AddParam("range_first_value", out IOutParam<int> range_first_value)
                .AddParam("range_last_value", out IOutParam<int> range_last_value)
                .ExecNonQuery();

**Comment by verdie-g** [comment]
https://github.com/verdie-g/StoredProcedureEFCore/blob/6171d12503cb1be10b2d842b2dec2cba8cec2304/StoredProcedureEFCore/IStoredProcBuilder.cs#L65
This overload accepts a `DbParameter` so can you pass a `SqlParameter` with a `SqlDbType.Variant`.

**Comment by guffy1234** [comment]
yes, this code is workable:

` var firstValueInRange = new SqlParameter("@range_first_value", SqlDbType.Variant)
            {
                Direction = ParameterDirection.Output
            };
            var lastValueInRange = new SqlParameter("@range_last_value", SqlDbType.Variant)
            {
                Direction = ParameterDirection.Output
            };
            await this.LoadStoredProc("sys.sp_sequence_get_range")
                .AddParam("@sequence_name", name)
                .AddParam("@range_size", range_size)
                .AddParam(firstValueInRange)
                .AddParam(lastValueInRange)
                .ExecNonQueryAsync();
            return new Tuple<int, int>((int)firstValueInRange.Value, (int)lastValueInRange.Value);`

but probably it would be nice to find some way how to handle the case in a more elegant way

**Comment by verdie-g** [comment]
There is no plan to add database specific extension.
