### ISSUE TITLE
Target .NET Standard

### ISSUE THREAD

**Issue by xKloc** [verdie-g/StoredProcedureEFCore#5]
Can you have this target .NET Standard, so it can be used in class libraries?

**Comment by verdie-g** [comment]
I'm not really familiar with .NET Standard but this library references _Microsoft.EntityFrameworkCore.Design_, will it be usable in any .NET project if I target .NET standard ?

**Comment by xKloc** [comment]
Correct, I actually just copied your files into a .Net Standard Class Library and was able to use them as is for my project.

**Comment by verdie-g** [comment]
Done
