### ISSUE TITLE
Performance concern over disposing connection

### ISSUE THREAD

**Issue by joseclament** [verdie-g/StoredProcedureEFCore#7]
Hi,
I have the following suggestions.
Each and every operation/s the connection is creating/recreating, closing and disposing. 
I assumes we only need to close the connection and not disposing it. The EF DB context should manage the dispose automatically, so we hence we can reuse the connection pool. Also check before opening and closing the connection if its already opened and closed respectively (Thread safe).

Regards,
Jose Clament

**Comment by verdie-g** [comment]
Hi, thanks for opening this issue.

In _StoredProcBuilder.Exec*_ methods, connection is indeed opened then closed for each request. Tell me if I'm wrong, but I think the Close method just mean the connection is disposed and can return to the connection pool to be reused and it is not destroyed.

Regarding the check for connection's state before opening or closing it, it would probably be necessary if the _DbConnection_ object was shared between threads, but I can't see any case where you would do that.
