### ISSUE TITLE
Support for Structured parameters

### ISSUE THREAD

**Issue by nycbauer** [verdie-g/StoredProcedureEFCore#8]
I am trying to pass in a DataTable as a parameter to a stored procedure, and it's not working. I am getting a NotSupportedException.

After looking quickly, it appears to be because this is not supporting SQL Server specifically, which allows for a DataTable to be passed as a parameter with the SqlDbType.Structured.

Is there plan for future support of SQL Server specifically?

**Comment by verdie-g** [comment]
I don't think I will take the time to make a specific SQL Server support since stored procedures support in entity framework is planned for 2.1. My project will be soon deprecated.

**Comment by korifeich** [comment]
HI! I also need this feature.

I've added method that accepts DBParameter as input, so you can pass SqlParameter in there as it is inherited from DBParameter and everything should work fine.

**Comment by verdie-g** [comment]
With this PR you will be able to pass a SqlParameter but the mapping probably won't work for a DataTable.

**Comment by korifeich** [comment]
As fat as  know all you need it just to set SqlParameter Value to be you DataTable value as well as Set TypeName (in case you are mapping to a particular type in DB).
`DataTable addedCategories = CategoriesDataTable.GetChanges(DataRowState.Added);  
 var parameter = new SqlParameter(name, SqlDbType.Structured);
parameter.Value = addedCategories ;
parameter.TypeName = typeName;`

That is all with parameter generation you can not pass it so SP builder method I've created.

**Comment by JohnKuan** [comment]
I think what was mentioned by @korifeich will work for SqlParameter. I am currently passing this in the standard `ExecuteSqlCommandAsync` and it adds a DataTable according to the SP I have defined. 

    new SqlParameter("@my_table_name", table) { TypeName = "my_table_type", SqlDbType = SqlDbType.Structured }

**Comment by JohnKuan** [comment]
If this is on the latest release on Nuget, I can start using this package to simplify my SP functions.

**Comment by verdie-g** [comment]
Available in StoredProcedureEFCore 0.3.13. Thank you.
