### ISSUE TITLE
Passing null value to the AddParameter<T> method does not pass parameter to StoredProcedure.

### ISSUE THREAD

**Issue by korifeich** [verdie-g/StoredProcedureEFCore#9]
I've tried to pass null value as a value of the Stored Procedure parameter:
` spBuild.AddParam(param.Name, (long?)null); ` 

As a result this parameter is not passed into the Stored Procedure. 
This issue was reproduced with SQLServer.

**Comment by verdie-g** [comment]
Thanks. I was aware of this problem but I didn't find a good solution.

I didn't know T was comparable to null.
